status_ready = '就绪'
status_reading = '读取中...'
status_analyzing = '分析中...'
status_updating = '更新中...'

msg_error = '错误'
msg_warning = '警告'

msg_file_unselected = '未选择文件'
msg_select_file = '选择视频文件'
msg_waiting = '请稍候'
msg_exporting = '正在导出...'

main_title = 'QTracker'
main_widget_open_file = '打开文件'
main_widget_settings = '设置'
main_widget_load_file = '加载视频'
main_widget_analyze = '粒子分析'
main_widget_track = '轨迹跟踪'
main_widget_export = '导出视频'
main_widget_select = '选择'
main_widget_move = '移动'
main_widget_add = '添加'
main_widget_crop = '裁剪'
main_widget_combine = '合并'
main_widget_frames = '帧'
main_widget_play = '播放'
main_widget_filter = '粒子筛选'
main_widget_show_particle = '显示/隐藏粒子'
main_widget_show_mark = '显示/隐藏标记'
main_widget_show_frame = '显示/隐藏帧'
main_widget_show_trajectory = '显示/隐藏轨迹'

settings_title = '设置'
settings_tab_analyze = '分析'
settings_tab_display = '显示'
settings_tab_export = '导出'
settings_widget_median_blur = '中值模糊'
settings_widget_opening_size = '开运算'
settings_widget_gaussian_blur = '高斯模糊'
settings_widget_closing_size = '闭运算'
settings_widget_apply_hist_eq = '直方图均衡化'
settings_widget_adaptive_hist_eq = '均衡化次数'
settings_widget_bilateral_filter = '双边滤波(size/color/space)'
settings_widget_search_radius = '搜索半径'
settings_widget_minimum_detect_area = '最小检测面积'
settings_widget_maximum_detect_area = '最大检测面积'
settings_widget_memory_frames = '记忆帧数'
settings_widget_threshold = '阈值'
settings_widget_derivative_order = 'Sobel差分阶数'
settings_widget_kernel_size = 'Sobel核大小'
settings_widget_split_particle = '分割粒子'
settings_widget_particle_radius_for_split = '分割粒子尺寸'
settings_widget_fit_to_screen = '适应屏幕'
settings_widget_skip_frames = '跳过帧'
settings_widget_from_frames = '起始帧'
settings_widget_to_frames = '结束帧'
settings_widget_particle_color = '粒子颜色'
settings_widget_particle_size = '粒子大小'
settings_widget_mark_color = '标记颜色'
settings_widget_mark_size = '标记大小'
settings_widget_same_mark_color_with_particle = '与粒子颜色相同'
settings_widget_trajectory_color = '轨迹颜色'
settings_widget_trajectory_size = '轨迹宽度'
settings_widget_same_trajectory_color_with_particle = '与粒子颜色相同'
settings_widget_enable_speed_color = '颜色与速度相关'
settings_widget_min_speed = '最小速度'
settings_widget_max_speed = '最大速度'
settings_widget_export_param = '导出参数'
settings_widget_export_scale = '缩放'
settings_widget_export_speed = '速度'
settings_widget_show_time = '显示时间'
settings_widget_show_info = '显示信息'

color_edit_widget_add = '添加颜色'
color_edit_widget_delete = '删除颜色'
color_edit_widget_random = '随机颜色'






