from collections import namedtuple

from PySide6.QtGui import QColor, QFont

setting_item = namedtuple('setting_item', ['section', 'key', 'default_value'])

main_width = setting_item('main', 'width', 1280)
main_height = setting_item('main', 'height', 1080)

median_blur = setting_item('analyze', 'median_blur', 1)
gaussian_blur = setting_item('analyze', 'gaussian_blur', 3)
opening_size = setting_item('analyze', 'opening_size', 1)
closing_size = setting_item('analyze', 'closing_size', 1)
apply_hist_eq = setting_item('analyze', 'apply_hist_eq', False)
adaptive_hist_eq = setting_item('analyze', 'adaptive_hist_eq', 0)
bilateral_size = setting_item('analyze', 'bilateral_size', 6)
bilateral_color = setting_item('analyze', 'bilateral_color', 75)
bilateral_space = setting_item('analyze', 'bilateral_space', 75)
search_radius = setting_item('analyze', 'search_radius', 40)
minimum_area_for_detection = setting_item('analyze', 'minimum_area_for_detection', 30)
maximum_area_for_detection = setting_item('analyze', 'maximum_area_for_detection', 3000)
memory_frames = setting_item('analyze', 'memory_frames', 40)
threshold = setting_item('analyze', 'threshold', 175)
derivative_order = setting_item('analyze', 'derivative_order', 1)
kernel_size = setting_item('analyze', 'kernel_size', 5)
split_circular_particles = setting_item('analyze', 'split_circular_particles', False)
split_radius = setting_item('analyze', 'split_radius', 10)
fit_to_screen = setting_item('analyze', 'fit_to_screen', True)
show_binary_image = setting_item('analyze', 'show_binary_image', False)
skip_frames = setting_item('analyze', 'skip_frames', 0)
from_frames = setting_item('analyze', 'from_frames', 1)
to_frames = setting_item('analyze', 'to_frames', -1)
file_path = setting_item('analyze', 'file_path', None)
dir_path = setting_item('analyze', 'dir_path', None)
frame_quality = setting_item('analyze', 'frame_quality', 80)
fps = setting_item('analyze', 'fps', -1)

particle_color = setting_item('display', 'particle_color', QColor(0, 255, 0))
particle_size = setting_item('display', 'particle_size', 4)
show_particle = setting_item('display', 'show_particle', True)
mark_color = setting_item('display', 'mark_color', QColor(255, 0, 0))
mark_size = setting_item('display', 'mark_size', 4)
mark_font = setting_item('display', 'mark_font', QFont('SimHei'))
show_mark = setting_item('display', 'show_mark', True)
same_mark_color_with_particle = setting_item('display', 'same_mark_color_with_particle', False)
trajectory_color = setting_item('display', 'trajectory_color', QColor(0, 0, 255))
trajectory_size = setting_item('display', 'trajectory_size', 2)
show_trajectory = setting_item('display', 'show_trajectory', True)
same_trajectory_color_with_particle = setting_item('display', 'same_trajectory_color_with_particle', False)
enable_trajectory_speed_color = setting_item('display', 'enable_trajectory_speed_color', False)
trajectory_speed_color = setting_item('display', 'trajectory_speed_color',
                                      [QColor(255, 0, 0), QColor(0, 255, 0), QColor(0, 0, 255)])
max_speed = setting_item('display', 'max_speed', 100)
min_speed = setting_item('display', 'min_speed', 0)
index_filter = setting_item('display', 'index_filter', [])

export_scale = setting_item('export', 'export_scale', 1)
export_speed = setting_item('export', 'export_speed', 1)
export_show_time = setting_item('export', 'show_time', False)
export_show_info = setting_item('export', 'show_info', False)
