from collections import namedtuple

default_setting = namedtuple('default_setting', ['section', 'key', 'value'])

main_width = default_setting('main', 'width', 1280)
main_height = default_setting('main', 'height', 1080)

median_blur = default_setting('analyze', 'median_blur', 1)
gaussian_blur = default_setting('analyze', 'gaussian_blur', 3)
opening_size = default_setting('analyze', 'opening_size', 1)
closing_size = default_setting('analyze', 'closing_size', 1)
apply_hist_eq = default_setting('analyze', 'apply_hist_eq', False)
adaptive_hist_eq = default_setting('analyze', 'adaptive_hist_eq', 0)
bilateral_size = default_setting('analyze', 'bilateral_size', 6)
bilateral_color = default_setting('analyze', 'bilateral_color', 75)
bilateral_space = default_setting('analyze', 'bilateral_space', 75)
search_radius = default_setting('analyze', 'search_radius', 40)
minimum_area_for_detection = default_setting('analyze', 'minimum_area_for_detection', 30)
maximum_area_for_detection = default_setting('analyze', 'maximum_area_for_detection', 3000)
memory_frames = default_setting('analyze', 'memory_frames', 40)
threshold = default_setting('analyze', 'threshold', 175)
derivative_order = default_setting('analyze', 'derivative_order', 1)
kernel_size = default_setting('analyze', 'kernel_size', 5)
split_circular_particles = default_setting('analyze', 'split_circular_particles', False)
split_radius = default_setting('analyze', 'split_radius', 10)
fit_to_screen = default_setting('analyze', 'fit_to_screen', True)
show_binary_image = default_setting('analyze', 'show_binary_image', False)
skip_frames = default_setting('analyze', 'skip_frames', 0)
from_frames = default_setting('analyze', 'from_frames', 1)
to_frames = default_setting('analyze', 'to_frames', -1)
file_path = default_setting('analyze', 'file_path', None)
dir_path = default_setting('analyze', 'dir_path', None)
